# Generated by Django 4.2.7 on 2023-11-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.TextField()),
                ('username', models.TextField()),
                ('photo', models.TextField()),
                ('phone_number', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('user_type', models.TextField()),
            ],
        ),
    ]
