# Generated by Django 4.2.7 on 2023-11-05 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('startDate', models.DateField(auto_now=True)),
                ('endDate', models.DateField(auto_now=True)),
                ('startTime', models.DateTimeField(auto_now=True)),
                ('endTime', models.DateTimeField(auto_now=True)),
                ('venue', models.CharField(max_length=200)),
                ('attachment', models.FileField(blank=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='EventAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
